# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /downloadFile
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.zhenshu: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: Kindergarten-2022-23T6N8T59!
  # 令牌有效期, 单位分钟
  expireTime: 480

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.zhenshu.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 枚举类转换
  typeEnumsPackage: com.zhenshu.common.enums.**
  global-config:
    db-config:
      logic-delete-field: del_flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 标题
  title: 幼儿园管理系统
  # 描述
  description: 幼儿园管理系统
  # 业务接口
  terms-of-service-url: http://localhost:8080
  license: Powered By ZS
  # 分组
  kg-home:
    groupName: 校区-首页
    basePackage: com.zhenshu.api.kg.home
    pathMapping: /
  kg-work:
    groupName: 校区-日常工作
    basePackage: com.zhenshu.api.kg.work
    pathMapping: /
  kg-health:
    groupName: 校区-健康管理
    basePackage: com.zhenshu.api.kg.health
    pathMapping: /
  kg-finance:
    groupName: 校区-财务管理
    basePackage: com.zhenshu.api.kg.finance
    pathMapping: /
  kg-base:
    groupName: 校区-校区功能
    basePackage: com.zhenshu.api.kg.base
    pathMapping: /
  bloc:
    groupName: 集团接口
    basePackage: com.zhenshu.api.bloc
    pathMapping: /
  platform:
    groupName: 平台接口
    basePackage: com.zhenshu.api.platform
    pathMapping: /
  ruoyi:
    groupName: 若依原生接口
    basePackage: com.zhenshu.api.ruoyi
    pathMapping: /


# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 接口文档增强模式配置，文档地址：https://doc.xiaominfo.com/knife4j/documentation/enhance.html
knife4j:
  # 安全校验
  basic:
    enable: false
    # 账号
    username: admin
    # 密码
    password: 123
  # 配置
  setting:
    # 是否显示界面中 SwaggerModel 功能
    enableSwaggerModels: false
    # 是否在每个 Debug 调试栏后显示刷新变量按钮，默认不显示
    enableReloadCacheParameter: false
    # 是否开启界面中对某接口的版本控制，如果开启，后端变化后 Ui 界面会存在小蓝点
    enableVersion: false

# app 配置
app-config:
  profile: ./downloadFile/
  uploadLimit: ["BMP", "JPG", "JPEG", "PNG", "TIF", "GIF", "PCX", "TGA", "EXIF", "FPX", "SVG", "CDR", "PCD", "DXF", "UFO", "EPS", "RAW", "WMF", "WEBP", "MP4", "AVI", "NAVI", "DV-AVI", "DIVX", "MOV", "ASF", "WMV", "RM", "RMVB", "MPG", "FLV"]

# cdn
aliyun:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:
  address:
  projectName:
